onboarding = false

[keys]
prefix = "ctrl+s"
split_vertical = "prefix+|"
split_horizontal = "prefix+minus"
new_tab = "prefix+t"
new_workspace = "prefix+n"
previous_workspace = "alt+left"
next_workspace = "alt+right"

[ui.sound]
enabled = false

[ui]
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = true


[ui.notifications]
agent_blocked = false
agent_done = false

[theme]
name = "dracula"
auto_switch = false

[ui.toast]
delivery = "off"

[experimental]
pane_history = true

